# Generated by Django 2.1.1 on 2018-10-26 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='cantidad2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='cantidad3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='descripcion_material4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='descripcion_material5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='impresion_retiro4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='impresion_retiro5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='impresion_tiro4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='impresion_tiro5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='laminado4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='laminado5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='material4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='material5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='medida_alto_4',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='medida_alto_5',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='medida_ancho_4',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='medida_ancho_5',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='troquelado4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='troquelado5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='uv4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='uv5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
