# Generated by Django 2.1 on 2018-10-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_auto_20181026_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='num_ot_relacionada',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='solicitud_ot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
