# Generated by Django 2.1.1 on 2018-12-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20181117_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='permiso_borrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenessolicitadas',
            name='permiso_borrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cotizaciones_borradas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ordenes_borradas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre_razon_social',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes_ot',
            name='nombre_razon_social',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='descripcion_material',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='detalles',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='descripcion_material_ot',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='detalles_ot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='forma_empaque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_retiro2_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_retiro3_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_retiro4_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_retiro5_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_retiro_ot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_tiro2_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_tiro3_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_tiro4_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_tiro5_ot',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='impresion_tiro_ot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenessolicitadas',
            name='troquelado_ot',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
