# Generated by Django 2.1.1 on 2019-01-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0007_auto_20181210_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales_gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=40, unique=True)),
                ('usuario', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesGigantografia',
            fields=[
                ('num_solicitud_ot', models.AutoField(primary_key=True, serialize=False)),
                ('vendedor_ot', models.CharField(blank=True, max_length=20)),
                ('trabajo_ot', models.CharField(max_length=40)),
                ('tipo_trabajo_ot', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad_ot', models.IntegerField()),
                ('material_ot', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_material_ot', models.CharField(blank=True, max_length=40, null=True)),
                ('medida_alto_ot', models.FloatField(blank=True, null=True)),
                ('medida_ancho_ot', models.FloatField(blank=True, null=True)),
                ('troquelado_ot', models.CharField(blank=True, max_length=40, null=True)),
                ('material2_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('medida_alto_2_ot', models.FloatField(blank=True, default=0, null=True)),
                ('medida_ancho_2_ot', models.FloatField(blank=True, default=0, null=True)),
                ('descripcion_material2_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('troquelado2_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('material3_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('medida_alto_3_ot', models.FloatField(blank=True, default=0, null=True)),
                ('medida_ancho_3_ot', models.FloatField(blank=True, default=0, null=True)),
                ('descripcion_material3_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('troquelado3_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('material4_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('medida_alto_4_ot', models.FloatField(blank=True, default=0, null=True)),
                ('medida_ancho_4_ot', models.FloatField(blank=True, default=0, null=True)),
                ('descripcion_material4_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('troquelado4_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('material5_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('medida_alto_5_ot', models.FloatField(blank=True, default=0, null=True)),
                ('medida_ancho_5_ot', models.FloatField(blank=True, default=0, null=True)),
                ('descripcion_material5_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('troquelado5_ot', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('fecha_solicitada_ot', models.DateTimeField(auto_now_add=True)),
                ('detalles_ot', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_completada_ot', models.DateTimeField(blank=True, null=True)),
                ('cotizador_ot', models.CharField(blank=True, max_length=20)),
                ('fecha_entrega_ot', models.DateField(blank=True, null=True)),
                ('fecha_entregada', models.DateField(blank=True, null=True)),
                ('procesado_por_ot', models.CharField(blank=True, default=' ', max_length=25)),
                ('estado_ot', models.CharField(blank=True, default='Por aperturar', max_length=25)),
                ('num_ot_relacionada', models.CharField(blank=True, default='', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=80)),
                ('persona_recibe', models.CharField(blank=True, max_length=20)),
                ('forma_empaque', models.CharField(blank=True, max_length=50)),
                ('arte', models.BooleanField(default=False)),
                ('prueba_de_color', models.BooleanField(default=False)),
                ('precio_ot', models.FloatField(blank=True, default=0, null=True)),
                ('material_confirmado', models.BooleanField(default=False)),
                ('permiso_borrar', models.BooleanField(default=False)),
                ('nombre_cliente_ot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_gig_ot', to='cotizacion.Clientes_ot')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeTrabajo_gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.CharField(max_length=40, unique=True)),
                ('usuario', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
