# Generated by Django 2.1 on 2019-01-31 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0009_auto_20190116_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_cot',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 30), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_ot',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 30), null=True),
        ),
    ]
