# Generated by Django 2.1 on 2019-01-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0009_auto_20190116_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materiales_gig',
        ),
        migrations.RemoveField(
            model_name='ordenesgigantografia',
            name='nombre_cliente_ot',
        ),
        migrations.DeleteModel(
            name='TipoDeTrabajo_gig',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='cotizaciones_borradas_mes',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='cotizaciones_borradas_totales',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_ultima_cot',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_ultima_ot',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ordenes_borradas_mes',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ordenes_borradas_totales',
        ),
        migrations.DeleteModel(
            name='OrdenesGigantografia',
        ),
    ]
