# Generated by Django 2.1.1 on 2019-02-08 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0010_auto_20190130_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='bloqeuado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_cot',
            field=models.DateField(blank=True, default=datetime.date(2019, 2, 8), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_ot',
            field=models.DateField(blank=True, default=datetime.date(2019, 2, 8), null=True),
        ),
    ]
