# Generated by Django 2.1.1 on 2019-02-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0011_auto_20190208_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='bloqeuado',
            new_name='bloqueado',
        ),
    ]
