# Generated by Django 2.1 on 2019-01-20 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0012_auto_20190120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_cot',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 20), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_ot',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 20), null=True),
        ),
    ]
