# Generated by Django 2.1 on 2019-01-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_auto_20181113_1425'),
        ('cotizacion', '0013_auto_20190120_1253'),
    ]

    operations = [
    ]
