# Generated by Django 2.1 on 2019-02-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0010_auto_20190130_2116'),
        ('cotizacion', '0014_merge_20190120_1334'),
    ]

    operations = [
    ]
