# Generated by Django 2.1 on 2019-02-01 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0015_merge_20190131_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_cot',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 31), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_ultima_ot',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 31), null=True),
        ),
    ]
