# Generated by Django 2.1 on 2019-03-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0016_auto_20190131_2008'),
        ('cotizacion', '0012_auto_20190208_0942'),
    ]

    operations = [
    ]
